options:
    prefix: &8[&4Demon Farms&8]&7
    borders: &7&m          &c&m            &4&m            &c&m            &7&m          &r
    sellwanditem: blaze rod
    sellwandname1: &4Sellwand &7| &c1.1x
    sellwandname2: &4Sellwand &7| &c1.2x
    sellwandname3: &4Sellwand &7| &c1.3x
    sellwandname4: &4Sellwand &7| &c1.4x
    sellwandname5: &4Sellwand &7| &c1.5x
    sellwandname6: &4Sellwand &7| &c1.6x
    sellwandname7: &4Sellwand &7| &c1.7x

command /sellwands [<player>] [<integer>]:
    trigger:
        if arg-1 or arg-2 is not set:
            send "{@prefix} &cUsage: &7/sellwands (player) (level)"
            stop
        if sender is not console:
            if hasPermission(sender, "sellwands.admin") = false:
                send "{@prefix} You don't have permission for this!" to sender
                stop
        if arg-2 = 1:
            give 1 of {@sellwanditem} named "{@sellwandname1}" with lore "&7(Right-Click to use)" to arg-1
            send "{@prefix} You gave &4%arg-1% &7a {@sellwandname1}!" to sender
            alertStaff("&4%sender% &cgave &4%arg-1% &ca {@sellwandname1}")
        if arg-2 = 2:
            give 1 of {@sellwanditem} named "{@sellwandname2}" with lore "&7(Right-Click to use)" to arg-1
            send "{@prefix} You gave &4%arg-1% &7a {@sellwandname2}!" to sender
            alertStaff("&4%sender% &cgave &4%arg-1% &ca {@sellwandname2}")
        if arg-2 = 3:
            give 1 of {@sellwanditem} named "{@sellwandname3}" with lore "&7(Right-Click to use)" to arg-1
            send "{@prefix} You gave &4%arg-1% &7a {@sellwandname3}!" to sender
            alertStaff("&4%sender% &cgave &4%arg-1% &ca {@sellwandname3}")
        if arg-2 = 4:
            give 1 of {@sellwanditem} named "{@sellwandname4}" with lore "&7(Right-Click to use)" to arg-1
            send "{@prefix} You gave &4%arg-1% &7a {@sellwandname4}!" to sender
            alertStaff("&4%sender% &cgave &4%arg-1% &ca {@sellwandname4}")
        if arg-2 = 5:
            give 1 of {@sellwanditem} named "{@sellwandname5}" with lore "&7(Right-Click to use)" to arg-1
            send "{@prefix} You gave &4%arg-1% &7a {@sellwandname5}!" to sender
            alertStaff("&4%sender% &cgave &4%arg-1% &ca {@sellwandname5}")
        if arg-2 = 6:
            give 1 of {@sellwanditem} named "{@sellwandname6}" with lore "&7(Right-Click to use)" to arg-1
            send "{@prefix} You gave &4%arg-1% &7a {@sellwandname6}!" to sender
            alertStaff("&4%sender% &cgave &4%arg-1% &ca {@sellwandname6}")
        if arg-2 = 7:
            give 1 of {@sellwanditem} named "{@sellwandname7}" with lore "&7(Right-Click to use)" to arg-1
            send "{@prefix} You gave &4%arg-1% &7a {@sellwandname7}!" to sender
            alertStaff("&4%sender% &cgave &4%arg-1% &ca {@sellwandname7}")

on right click on chest or hopper:
    if name of player's tool != "{@sellwandname1}" or "{@sellwandname2}" or "{@sellwandname3}" or "{@sellwandname4}" or "{@sellwandname5}" or "{@sellwandname6}" or "{@sellwandname7}":
        stop
    if name of player's tool = "{@sellwandname1}" or "{@sellwandname2}" or "{@sellwandname3}" or "{@sellwandname4}" or "{@sellwandname5}" or "{@sellwandname6}" or "{@sellwandname7}":
        cancel event
        if inventory of event-block does not contain wheat or carrot or potato or nether wart or melon slice or pumpkin or sugar cane or cactus:
            send "{@prefix} You don't have any items to sell!" to player
            stop
        delete {shop::tempdata::wheatAmount::%uuid of player%}
        delete {shop::tempdata::carrotAmount::%uuid of player%}
        delete {shop::tempdata::potatoAmount::%uuid of player%}
        delete {shop::tempdata::netherwartAmount::%uuid of player%}
        delete {shop::tempdata::melonSliceAmount::%uuid of player%}
        delete {shop::tempdata::pumpkinAmount::%uuid of player%}
        delete {shop::tempdata::sugarCaneAmount::%uuid of player%}
        delete {shop::tempdata::cactusAmount::%uuid of player%}
        delete {shop::tempdata::sellList::%uuid of player%::*}
        if name of player's tool = "{@sellwandname1}":
            set {sellwands::tempdata::sellwandMultiplier::%uuid of player%} to 1.1
        if name of player's tool = "{@sellwandname2}":
            set {sellwands::tempdata::sellwandMultiplier::%uuid of player%} to 1.2
        if name of player's tool = "{@sellwandname3}":
            set {sellwands::tempdata::sellwandMultiplier::%uuid of player%} to 1.3
        if name of player's tool = "{@sellwandname4}":
            set {sellwands::tempdata::sellwandMultiplier::%uuid of player%} to 1.4
        if name of player's tool = "{@sellwandname5}":
            set {sellwands::tempdata::sellwandMultiplier::%uuid of player%} to 1.5
        if name of player's tool = "{@sellwandname6}":
            set {sellwands::tempdata::sellwandMultiplier::%uuid of player%} to 1.6
        if name of player's tool = "{@sellwandname7}":
            set {sellwands::tempdata::sellwandMultiplier::%uuid of player%} to 1.7
        if inventory of event-block contains wheat:
            set {shop::tempdata::wheatAmount::%uuid of player%} to amount of wheat in inventory of event-block
            remove {shop::tempdata::wheatAmount::%uuid of player%} of wheat from inventory of event-block
            add "&4x%{shop::tempdata::wheatAmount::%uuid of player%}% &7of &4wheat &7for &4$&4%{shop::tempdata::wheatAmount::%uuid of player%} * 1.75%" to {shop::tempdata::sellList::%uuid of player%::*}
        if inventory of event-block contains carrot:
            set {shop::tempdata::carrotAmount::%uuid of player%} to amount of carrot in inventory of event-block
            remove {shop::tempdata::carrotAmount::%uuid of player%} of carrot from inventory of event-block
            add "&4x%{shop::tempdata::carrotAmount::%uuid of player%}% &7of &4carrot &7for &4$&4%{shop::tempdata::carrotAmount::%uuid of player%} * 2%" to {shop::tempdata::sellList::%uuid of player%::*}
        if inventory of event-block contains potato:
            set {shop::tempdata::potatoAmount::%uuid of player%} to amount of potato in inventory of event-block
            remove {shop::tempdata::potatoAmount::%uuid of player%} of potato from inventory of event-block
            add "&4x%{shop::tempdata::potatoAmount::%uuid of player%}% &7of &4potato &7for &4$&4%{shop::tempdata::potatoAmount::%uuid of player%} * 3%" to {shop::tempdata::sellList::%uuid of player%::*}
        if inventory of event-block contains nether wart:
            set {shop::tempdata::netherwartAmount::%uuid of player%} to amount of nether wart in inventory of event-block
            remove {shop::tempdata::netherwartAmount::%uuid of player%} of nether wart from inventory of event-block
            add "&4x%{shop::tempdata::netherwartAmount::%uuid of player%}% &7of &4nether wart &7for &4$&4%{shop::tempdata::netherwartAmount::%uuid of player%} * 4.5%" to {shop::tempdata::sellList::%uuid of player%::*}
        if inventory of event-block contains melon slice:
            set {shop::tempdata::melonSliceAmount::%uuid of player%} to amount of melon slice in inventory of event-block
            remove {shop::tempdata::melonSliceAmount::%uuid of player%} of melon slice from inventory of event-block
            add "&4x%{shop::tempdata::melonSliceAmount::%uuid of player%}% &7of &4melon slice &7for &4$&4%{shop::tempdata::melonSliceAmount::%uuid of player%} * 0.2%" to {shop::tempdata::sellList::%uuid of player%::*}
        if inventory of event-block contains pumpkin:
            set {shop::tempdata::pumpkinAmount::%uuid of player%} to amount of pumpkin in inventory of event-block
            remove {shop::tempdata::pumpkinAmount::%uuid of player%} of pumpkin from inventory of event-block
            add "&4x%{shop::tempdata::pumpkinAmount::%uuid of player%}% &7of &4pumpkin &7for &4$&4%{shop::tempdata::pumpkinAmount::%uuid of player%} * 1%" to {shop::tempdata::sellList::%uuid of player%::*}
        if inventory of event-block contains sugar cane:
            set {shop::tempdata::sugarCaneAmount::%uuid of player%} to amount of sugar cane in inventory of event-block
            remove {shop::tempdata::sugarCaneAmount::%uuid of player%} of sugar cane from inventory of event-block
            add "&4x%{shop::tempdata::sugarCaneAmount::%uuid of player%}% &7of &4sugar cane &7for &4$&4%{shop::tempdata::sugarCaneAmount::%uuid of player%} * 1.3%" to {shop::tempdata::sellList::%uuid of player%::*}
        if inventory of event-block contains cactus:
            set {shop::tempdata::cactusAmount::%uuid of player%} to amount of cactus in inventory of event-block
            remove {shop::tempdata::cactusAmount::%uuid of player%} of cactus from inventory of event-block
            add "&4x%{shop::tempdata::cactusAmount::%uuid of player%}% &7of &4cactus &7for &4$&4%{shop::tempdata::cactusAmount::%uuid of player%} * 1.4%" to {shop::tempdata::sellList::%uuid of player%::*}
        set {_total} to ({shop::tempdata::wheatAmount::%uuid of player%} * 1.75) + ({shop::tempdata::carrotAmount::%uuid of player%} * 2) + ({shop::tempdata::potatoAmount::%uuid of player%} * 3) + ({shop::tempdata::netherwartAmount::%uuid of player%} * 4.5) + ({shop::tempdata::melonSliceAmount::%uuid of player%} * 0.2) + ({shop::tempdata::pumpkinAmount::%uuid of player%} * 1) + ({shop::tempdata::sugarCaneAmount::%uuid of player%} * 1.3) + ({shop::tempdata::cactusAmount::%uuid of player%} * 1.4)
        set {_multiplier} to getMultiplier(player)
        add ({boosters::localbooster::%uuid of player%::amount} - 1) to {_multiplier} if {boosters::localbooster::%uuid of player%::*} is set
        add ({boosters::globalbooster::amount} - 1) to {_multiplier} if {boosters::globalbooster::*} is set
        add ({sellwands::tempdata::sellwandMultiplier::%uuid of player%} - 0) to {_multiplier} if {sellwands::tempdata::sellwandMultiplier::%uuid of player%} is set
        set {_finishedAmount} to {_total} * {_multiplier}
        addBalance(player, {_finishedAmount})
        send "{@borders}" to player
        send "&4Sell: &c$&c%{_finishedAmount}%" to player
        send "&7 " to player
        loop {shop::tempdata::sellList::%uuid of player%::*}:
            send loop-value to player
        send "&7 " to player if {boosters::globalbooster::*} or {boosters::localbooster::%uuid of player%::*} is set
        send "&c(( GET A BOOSTER @ /BUY OR /GEMSHOP ))" to player if {boosters::globalbooster::*} and {boosters::localbooster::%uuid of player%::*} is not set
        send "&c(( MULTIPLIED BY YOUR LOCAL BOOSTER ))" to player if {boosters::localbooster::%uuid of player%::*} is set
        send "&c(( MULTIPLIED BY THE GLOBAL BOOSTER ))" to player if {boosters::globalbooster::*} is set
        send "{@borders}" to player